// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 68ba2c3132
// Version Date: Tue Jun  8 17:59:18 UTC 2021

package main

import (
	"flag"
	// This Service
	"godemo/gokit/All/echo-service/handlers"
	"godemo/gokit/All/echo-service/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	cfg := server.DefaultConfig
	cfg = handlers.SetConfig(cfg)

	server.Run(cfg)
}
